export default {
  title: 'Product Details',
  icon: 'mdi-alpha-p-box-outline',
  children: [
    { title: 'Product Types', to: 'product-details-product-types' },
    { title: 'Country', to: 'product-details-country' },
    { title: 'Master List', to: 'product-details-master-list' },
    { title: 'Material Types', to: 'product-details-material-types' },
    { title: 'Connection Types', to: 'product-details-connection-types' },
    { title: 'Generic Pipe', to: 'product-details-generic-pipe' },
    { title: 'Pipe Network Types', to: 'product-details-pipe-network-types' },
    { title: 'Common Fields', to: 'product-details-common-fields' },
    { title: 'Pipe Prms', to: 'product-details-pipe-prms' },
    { title: 'Normal Pipe Fitt Prms', to: 'product-details-normal-pipe-fitt-prms' },
    { title: 'Special Pipe Fitt Prms', to: 'product-details-special-pipe-fitt-prms' },
    { title: 'DWV Pipe Fitt Prms', to: 'product-details-dwv-pipe-fitt-prms' },
    { title: 'Pipe Fitt Types', to: 'product-details-pipe-fitt-types' },
    { title: 'Plbg Fixs Prms', to: 'product-details-plbg-fixs-prms' },
    { title: 'Valves Prms', to: 'product-details-valves-prms' },
    { title: 'Mech Equip Prms', to: 'product-details-mech-equip-prms' },
  ],
}
